import type { Metadata } from "next";
import { Mohave } from "next/font/google"

import "./globals.css";

const mohave = Mohave({
  variable: "--font-mohave",
  subsets: ['latin', 'latin-ext'],
  // weight: ["400", "700"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mohave.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
