import type { Metadata } from "next";
import { Oswald } from "next/font/google"
import "./globals.css";
import { Navbar } from "@/components/Navbar";


const font  = Oswald({
  variable: "--font-default",
  subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
