import type { Metadata } from "next";
import { Oswald } from "next/font/google"

import "./globals.css";

// const font = Mohave({
//   variable: "--font-default",
//   subsets: ['latin', 'latin-ext'],
//   // weight: ["400", "700"]
// })

const font  = Oswald({
  variable: "--font-default",
  subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
